

name: nlnet
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version constraint for TensorFlow 1.x compatibility
  - python=3.7
  
  # Core ML Dependencies
  - tensorflow=1.15.5
  - pip
  
  # Data Processing
  - pandas=1.3.5
  - numpy=1.21.6
  
  # Development & Testing
  - pytest>=7.0.1
  - black=22.3.0
  - pre-commit>=2.21.0
  
  # Utilities
  - tqdm>=4.65.0
  - requests>=2.31.0
  
  # Code Analysis
  - mccabe>=0.7.0
  
  # Additional pip packages that aren't available in conda
  - pip:
    - guesslang==2.0.1
    - loguru>=0.7.0
    - supabase>=1.0.3
    - ruff>=0.1.3
    - ast>=0.0.2